version: '3'

services:
  stigid:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    container_name: stigid
    image: registry.docker.bland.work:443/stigid
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP
      - PORT
      - EXTERNAL_URL
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
