name: build-and-push
on:
  push:
    tags:
      - release/*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        uses: dawidd6/action-get-tag@v1.1.0
        id: tag
      - name: Set env
        run: echo "RELEASE_VERSION=${{steps.tag.outputs.tag}}" | sed 's/release\///g' >> $GITHUB_ENV
      - name: Login to registry.docker.bland.work
        uses: docker/login-action@v2
        with:
          registry: registry.docker.bland.work:443
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./
          file: ./docker/node/Dockerfile
          push: true
          from-cache: type=gha
          to-cache: type=gha
          tags: |
            registry.docker.bland.work:443/stigid:${{ env.RELEASE_VERSION }}
            registry.docker.bland.work:443/stigid:latest
